name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    name: Test before release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build adapter
        run: bun run build

      - name: Run tests
        run: bun run test:run

      - name: Run type check
        run: bun run typecheck

  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build adapter
        run: bun run build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build adapter
        run: bun run build

      - name: Create release archive
        run: |
          mkdir -p release
          cp -r dist release/
          cp package.json README.md LICENSE release/
          tar -czf better-auth-turso-${{ steps.get_version.outputs.VERSION }}.tar.gz -C release .

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            ## Changes in ${{ steps.get_version.outputs.VERSION }}

            See [CHANGELOG.md](CHANGELOG.md) for details.

            ## Installation

            ```bash
            npm install better-auth-turso@${{ steps.get_version.outputs.VERSION }}
            # or
            bun add better-auth-turso@${{ steps.get_version.outputs.VERSION }}
            ```
          draft: false
          prerelease: ${{ contains(steps.get_version.outputs.VERSION, '-') }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./better-auth-turso-${{ steps.get_version.outputs.VERSION }}.tar.gz
          asset_name: better-auth-turso-${{ steps.get_version.outputs.VERSION }}.tar.gz
          asset_content_type: application/gzip
